"""2024 Day 8 against AoC's published example."""

from __future__ import annotations

from aoc_spark.y2024 import day08 as spark_day08
from reference_python.y2024 import day08 as python_day08

EXAMPLE = """\
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"""

EXPECTED_PART1 = 14


def test_part1_spark(spark):
    assert spark_day08.part1(spark, EXAMPLE) == EXPECTED_PART1


def test_part1_reference():
    assert python_day08.part1(EXAMPLE) == EXPECTED_PART1
