"""Generate scripts/_examples.py from the test modules.

The notebooks show the same example data the suite asserts on. Rather than
retyping it (and letting the two drift), this pulls each example straight out
of its test module, then re-runs both implementations against it to confirm the
expected value is real before writing anything.

    PYTHONPATH=. python scripts/build_examples.py
"""

from __future__ import annotations

import importlib
import pprint
import sys
from pathlib import Path

# day -> (test module variable holding the example, expected part-1 answer, extra kwargs)
SPEC = {
    6: ("EXAMPLE", 41, {}),
    7: ("EXAMPLE", 3749, {}),
    8: ("EXAMPLE", 14, {}),
    9: ("DAY09", 1928, {}),
    10: ("DAY10", 36, {}),
    11: ("DAY11", 55312, {}),
    12: ("LARGE", 1930, {}),
    13: ("EXAMPLE", 480, {}),
    14: ("EXAMPLE", 12, {"width": 11, "height": 7}),
    15: ("LARGE", 10092, {}),
    16: ("FIRST", 7036, {}),
    17: ("MAIN", "4,6,3,5,6,3,5,2,1,0", {}),
    18: ("EXAMPLE", 22, {"size": 7, "fallen": 12}),
    19: ("EXAMPLE", 6, {}),
    20: ("EXAMPLE", 44, {"threshold": 2}),
}

ROOT = Path(__file__).resolve().parent.parent


def main() -> int:
    sys.path.insert(0, str(ROOT / "tests"))
    from aoc_spark.session import get_spark

    spark = get_spark("aoc-build-examples")
    out, failures = {}, []

    for day, (var, expected, kwargs) in SPEC.items():
        test_mod = importlib.import_module(f"test_day{day:02d}")
        data = getattr(test_mod, var)

        primary = importlib.import_module(f"aoc_spark.y2024.day{day:02d}")
        reference = importlib.import_module(f"reference_python.y2024.day{day:02d}")

        got_spark = primary.part1(spark, data, **kwargs)
        got_python = reference.part1(data, **kwargs)
        if got_spark != expected or got_python != expected:
            failures.append((day, expected, got_spark, got_python))
            print(f"day {day:2d}: FAIL spark={got_spark} python={got_python} expected={expected}")
            continue

        out[day] = {"data": data, "expected": expected, "kwargs": kwargs}
        print(f"day {day:2d}: ok ({expected})")

    spark.stop()
    if failures:
        print(f"\n{len(failures)} failure(s); not writing _examples.py")
        return 1

    body = (
        '"""Published AoC examples, generated by scripts/build_examples.py.\n\n'
        'Do not edit by hand -- regenerate instead.\n"""\n\n'
        "EXAMPLES = " + pprint.pformat(out, width=98, sort_dicts=True) + "\n"
    )
    (ROOT / "scripts" / "_examples.py").write_text(body)
    print(f"\nwrote scripts/_examples.py with {len(out)} days")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
