"""Notebook content spec for 2024 day 15."""

SPEC = {'angle': 'This is the day the repo uses Spark for nothing. `aoc_spark/y2024/day15.py` '
          'still takes a `SparkSession` to keep the interface uniform, and then never touches '
          'it. That is a deliberate answer, not a shortcut, and it is worth being precise about '
          'why.\n'
          '\n'
          '**The sequential dependency is total.** Move *k* reads the grid that move *k−1* '
          'produced. Not a summary of it — the grid. Whether `>` does anything depends on how '
          'far the run of boxes to the robot\'s right extends *right now*, which depends on '
          'every push that came before. There is no move you can evaluate without first '
          'evaluating all 20000 of its predecessors.\n'
          '\n'
          'Compare **day 3**, which looks equally sequential and is not. There the carried state '
          'was a single boolean, the transition was "keep the last non-null", and that is '
          'associative — so a window function computes all of it in one pass. The scan trick '
          'works whenever the carried state is small and the transition composes.\n'
          '\n'
          'Here the carried state is the entire 50×50 grid and the transition is a ray walk. '
          'Composing two moves without a grid to walk means representing "what this move does to '
          'an arbitrary grid", which is not smaller than the grid — so there is nothing to '
          'prefix-scan, and no window, join, or aggregate recovers the parallelism.\n'
          '\n'
          '**What a Spark version would actually cost.** The only faithful shape is one job per '
          'move: 20000 rounds, each reading the box positions, walking the ray, writing the '
          'updated set, and hitting an action so the driver can decide the next move. At even '
          '~50 ms of Spark Connect round-trip per round — optimistic for a plan that includes a '
          'join — that is roughly **17 minutes**. The Python simulation finishes the same 20000 '
          'moves in a few milliseconds.\n'
          '\n'
          'And there is nothing to win back at scale, because there is no scale. The grid is '
          '2500 cells with 623 boxes on it; that is one partition, and per move the real work is '
          'reading a handful of adjacent cells. **Spark\'s unit of work is larger than the entire '
          'problem.** The right call is a mutable `list[list[str]]` and a `while` loop.\n'
          '\n'
          'The one thing worth stealing from the implementation is the push itself. A run of *n* '
          'boxes shifting one step leaves every interior box exactly where it was — only the '
          'ends change. So instead of moving *n* boxes, teleport the near box to the far gap: '
          'write `O` at the first free cell past the run, and `.` where the robot lands. Two '
          'writes regardless of how long the run is.',
 'explore_code': "grid, moves = day15.parse(EXAMPLE)\n"
                 "boxes = sum(row.count('O') for row in grid)\n"
                 "print(f'{len(grid)}x{len(grid[0])} grid, {boxes} boxes, {len(moves)} moves')\n"
                 "print('moves start:', moves[:48])\n"
                 '\n'
                 '\n'
                 'def replay(grid, moves):\n'
                 '    """The same simulation, instrumented -- returns (blocked, gps)."""\n'
                 '    grid = [row[:] for row in grid]\n'
                 '    r, c = next(\n'
                 "        (r, c) for r, row in enumerate(grid) for c, ch in enumerate(row) if ch == '@'\n"
                 '    )\n'
                 '    blocked = 0\n'
                 '    for move in moves:\n'
                 '        dr, dc = day15.DELTAS[move]\n'
                 '        nr, nc = r + dr, c + dc\n'
                 '        er, ec = nr, nc\n'
                 "        while grid[er][ec] == 'O':\n"
                 '            er, ec = er + dr, ec + dc\n'
                 "        if grid[er][ec] == '#':\n"
                 '            blocked += 1\n'
                 '            continue\n'
                 "        grid[er][ec] = 'O' if (er, ec) != (nr, nc) else '.'\n"
                 "        grid[nr][nc] = '@'\n"
                 "        grid[r][c] = '.'\n"
                 '        r, c = nr, nc\n'
                 '    gps = sum(\n'
                 '        100 * r + c\n'
                 '        for r, row in enumerate(grid)\n'
                 "        for c, ch in enumerate(row)\n"
                 "        if ch == 'O'\n"
                 '    )\n'
                 '    return blocked, gps\n'
                 '\n'
                 '\n'
                 '# The answer only exists at the end of the sequence -- no prefix predicts it.\n'
                 'for n in (0, 1, 10, 100, 400, len(moves)):\n'
                 '    blocked, gps = replay(grid, moves[:n])\n'
                 "    print(f'after {n:>4} moves: {blocked:>4} blocked, GPS sum {gps}')\n"
                 '\n'
                 '# Same moves, different order: the state dependency, priced.\n'
                 'half = len(moves) // 2\n'
                 'shuffled = moves[half:] + moves[:half]\n'
                 "print('halves swapped ->', replay(grid, shuffled)[1])\n"
                 "print('reversed       ->', replay(grid, moves[::-1])[1])",
 'explore_md': '### Why there is nothing to parallelise\n'
               '\n'
               'The prefix table shows the answer wandering with no relationship to where it '
               'lands. The last two lines are the point: the *same multiset of moves* in a '
               'different order gives a different answer, so no reordering, batching, or '
               'partitioning of the move list is available.',
 'lesson': 'Python — sequential state mutation (and why Spark loses)',
 'notes': '- **Moves are wrapped across several lines** purely for the puzzle page\'s benefit. '
          '`"".join(move_block.split())` rejoins them; splitting on newlines and treating each '
          'line as a run would still work here, but treating a `\\n` as a move raises a `KeyError` '
          'on `DELTAS`.\n'
          '- `data.strip("\\n")` — **not** `.strip()`. A bare `strip()` would eat leading spaces, '
          'and while this input has none, the grid block is whitespace-significant.\n'
          '- The push shortcut (`grid[er][ec] = "O"`) relies on the run between the robot and the '
          'gap being **entirely boxes**, which the `while` loop guarantees, and on the near cell '
          'being overwritten by `@` immediately after. Reorder those two writes and a single-box '
          'push corrupts the grid.\n'
          "- The `(er, ec) != (nr, nc)` test distinguishes *pushed boxes* from *walked into empty "
          'space*. Without it, stepping into a `.` writes a phantom `O` behind the robot.\n'
          '- **The border is assumed to be solid `#`.** The ray walk has no bounds check at all — '
          'it relies on hitting a wall before running off the grid. That is true of every AoC '
          'input for this day and is the assumption most likely to bite anyone feeding it a '
          'hand-made grid.\n'
          '- GPS uses the **full map** coordinates including the wall border, so the top-left '
          'wall is `(0, 0)` and no offset is subtracted anywhere.\n'
          '- Exactly one `@` is assumed; `next(...)` on the generator takes the first and would '
          'raise `StopIteration` on a grid with none.\n'
          '- The puzzle publishes **two** examples: a small 8×8 one worth 2028 and a large 10×10 '
          'one with 700 moves worth **10092**. The repo uses the large one — checking against '
          'the wrong published answer is the easiest way to lose an hour here.',
 'summary': 'A warehouse map plus a long string of attempted robot moves.\n'
            '\n'
            'The map uses `#` for walls, `O` for boxes, `@` for the robot, `.` for floor. The '
            'moves are `^ v < >`, wrapped over several lines in the input but meant as one '
            'continuous sequence.\n'
            '\n'
            'When the robot moves into a box, it pushes it — and any unbroken run of boxes '
            'behind it — one step along. If **anything** in that run would be pushed into a '
            'wall, nothing moves at all, including the robot.\n'
            '\n'
            '- **Part 1** — run every move in order, then sum the **GPS coordinate** of each box: '
            '`100 × (distance from the top edge) + (distance from the left edge)`, measured '
            'against the full map, walls included.',
 'title': 'Warehouse Woes'}
