"""Notebook content spec for 2024 day 18."""

SPEC = {
    'angle': 'Breadth-first search on a 71×71 grid is ~5000 cells and ~20000 edge checks. '
             'CPython walks the whole thing in a couple of milliseconds using a `deque` and a '
             '`set`.\n'
             '\n'
             'The Spark framing is the same iterative-join shape as day 16, minus the priority '
             'queue: hold the current frontier as a DataFrame, cross-join it to a 4-row steps '
             'table, anti-join against `seen` to drop revisits, union into `seen`, repeat. The '
             'shortest path is 22 steps in the example and several hundred on the real grid — '
             '**that is one Spark job per BFS level**, each shuffling a frontier of '
             'at most a few dozen rows. The frontier is far too small to amortise a shuffle, '
             'and the level count is exactly what you cannot parallelise away: level *k+1* is '
             'undefined until level *k* is complete.\n'
             '\n'
             'The design decision actually worth studying here is the **signature**:\n'
             '\n'
             '```python\n'
             'def part1(spark, data, size: int = 71, fallen: int = 1024) -> int:\n'
             '```\n'
             '\n'
             'The published example is a 7×7 grid after 12 bytes; the real input is 71×71 after '
             '1024. Those are two different problem scales over the same input format. '
             'Hardcoding the real values would make the example untestable, and hardcoding the '
             'example values would make the answer wrong — so both become parameters with '
             'real-input defaults, and the test passes `size=7, fallen=12`. Note this is not '
             'the same as `size` being derivable from the data: the grid extends to '
             'coordinates no byte ever lands on, so it genuinely cannot be inferred.',
    'explore_code': 'from collections import deque\n'
                    '\n'
                    'SIZE, FALLEN = 7, 12  # the example scale; the real input is 71, 1024\n'
                    '\n'
                    "coords = [tuple(int(v) for v in line.split(',')) for line in "
                    'EXAMPLE.strip().splitlines()]\n'
                    'corrupted = set(coords[:FALLEN])\n'
                    "print(f'{len(coords)} bytes listed; only the first {FALLEN} have fallen "
                    "yet')\n"
                    '\n'
                    '# Same BFS as part1, but recording the distance of every cell it reaches.\n'
                    'goal = (SIZE - 1, SIZE - 1)\n'
                    'dist = {(0, 0): 0}\n'
                    'queue = deque([(0, 0)])\n'
                    'levels = []\n'
                    'while queue:\n'
                    '    levels.append(len(queue))\n'
                    '    for _ in range(len(queue)):  # one BFS level = one Spark job\n'
                    '        x, y = queue.popleft()\n'
                    '        for dx, dy in day18.STEPS:\n'
                    '            nxt = (x + dx, y + dy)\n'
                    '            if not (0 <= nxt[0] < SIZE and 0 <= nxt[1] < SIZE):\n'
                    '                continue\n'
                    '            if nxt in corrupted or nxt in dist:\n'
                    '                continue\n'
                    '            dist[nxt] = dist[(x, y)] + 1\n'
                    '            queue.append(nxt)\n'
                    '\n'
                    '# The grid, with each reachable cell showing its distance mod 10.\n'
                    'for y in range(SIZE):\n'
                    '    row = []\n'
                    '    for x in range(SIZE):\n'
                    '        if (x, y) in corrupted:\n'
                    "            row.append('#')\n"
                    '        elif (x, y) in dist:\n'
                    '            row.append(str(dist[(x, y)] % 10))\n'
                    '        else:\n'
                    "            row.append('.')\n"
                    "    print(' '.join(row))\n"
                    '\n'
                    "print()\nprint(f'reached the exit {goal} in {dist[goal]} steps, visiting "
                    "{len(dist)} of {SIZE * SIZE} cells')\n"
                    "print(f'BFS levels (frontier sizes): {levels}')\n"
                    "print(f'-> {len(levels)} sequential rounds, largest frontier {max(levels)} "
                    "cells')",
    'explore_md': '### The distance field, and the levels it took\n'
                  '\n'
                  'The grid below shows each reachable cell labelled with its BFS distance '
                  '(mod 10), `#` for corrupted, `.` for unreachable. Underneath is the frontier '
                  'size at each level — that list *is* the sequential dependency, and its '
                  'length is how many Spark jobs a distributed version would submit.',
    'lesson': 'Python — BFS with the grid scale as a parameter',
    'notes': '- **`size` and `fallen` are parameters, not constants.** The example is 7×7 after '
             '12 bytes; the real input is 71×71 after 1024. Defaults are the real-input values, '
             'and the notebook/test pass `size=7, fallen=12` for the example. Get these '
             'backwards and you get a plausible number that is simply wrong.\n'
             '- `size` is the **side length**, so valid coordinates are `0..size-1` and the goal '
             'is `(size-1, size-1)` — `70,70` for the real input, not `71,71`. The puzzle text '
             'states the range as `0 to 70`, which is the off-by-one waiting to happen.\n'
             '- Coordinates are **`x,y` = column,row**, not row,col. It happens not to matter '
             'here because the grid is square and start/goal are both on the diagonal, so a '
             'transposed reading gives the same answer — which is exactly the kind of luck that '
             'hides the bug until part 2 or a non-square grid.\n'
             '- `seen` is marked at **enqueue** time, not dequeue. Marking on dequeue lets the '
             'same cell enter the queue several times before it is first processed; the answer '
             'stays correct but the queue bloats.\n'
             '- The input lists more bytes than `fallen`; the slice `[:fallen]` is what makes '
             'the rest invisible. The remaining bytes are not junk — they are there for part 2.\n'
             '- Unreachable goal returns `-1` rather than raising. With the real defaults the '
             'grid is still traversable after 1024 bytes, so part 1 never sees it.',
    'summary': 'A list of `x,y` coordinates — bytes falling one per nanosecond into a square '
               'memory grid, in the order given. A fallen byte **corrupts** its coordinate; '
               'corrupted cells cannot be entered.\n'
               '\n'
               'You start at the top-left `(0,0)` and want the exit at the bottom-right corner. '
               'Moves are up/down/left/right, one cell at a time, and you cannot leave the '
               'grid.\n'
               '\n'
               '- **Part 1** — let the first *N* bytes fall, then find the minimum number of '
               'steps from corner to corner.\n'
               '\n'
               'The two scales matter: the published example is a **7×7 grid after 12 bytes** '
               '(answer 22), while the real input is a **71×71 grid after 1024 bytes**. Same '
               'format, different constants.',
    'title': 'RAM Run',
}
