"""Notebook content spec for 2024 day 10."""

SPEC = {'angle': 'A graph search where **the depth is known in advance**, which is what makes it '
          'a clean fit for Spark.\n'
          '\n'
          'Because every step must gain exactly one height, the trail graph is a DAG with '
          'exactly nine levels. There is no fixed point to iterate to and no visited-set to '
          'maintain — just `for height in range(1, 10)`, nine joins, done. That is the property '
          'worth noticing: most BFS-in-Spark writeups fight a `while` loop with a convergence '
          'check, and this puzzle hands you the loop bound for free.\n'
          '\n'
          'The frontier carries **pairs**, not positions: `(trailhead, current cell)`. Carrying '
          'the origin through every join is what lets all 233 trailheads be searched in the '
          'same nine queries instead of one search per trailhead. At the end the frontier is '
          'exactly the relation "trailhead *t* can reach summit *s*", so the answer is `count()` '
          '— the sum of the scores never has to be computed as a sum at all.\n'
          '\n'
          'Each step is `crossJoin` against a 4-row directions table (small enough that Spark '
          'broadcasts it) followed by an equi-join on the offset coordinates. The `.distinct()` '
          'after each step is doing real semantic work: a *score* counts **distinct reachable '
          'nines**, so collapsing duplicate paths as you go is both the correct definition and '
          'the thing that stops the frontier from growing path-count-shaped.\n'
          '\n'
          'Honest scale note: nine sequential Spark stages over a 48×48 grid take about **1.2 '
          's**, while the memoised DFS in `reference_python/y2024/day10.py` finishes in '
          'milliseconds. The relational shape is the one that would keep working on a grid that '
          'does not fit in memory; it is not the one that wins on this grid.',
 'explore_code': 'from pyspark.sql import functions as F\n'
                 '\n'
                 'grid = day10.cells(spark, EXAMPLE).cache()\n'
                 "grid.groupBy('h').count().orderBy('h').show()\n"
                 '\n'
                 "steps = spark.createDataFrame(day10.STEPS, 'dr INT, dc INT')\n"
                 'frontier = grid.filter(F.col("h") == 0).select(\n'
                 '    F.col("r").alias("sr"), F.col("c").alias("sc"), "r", "c"\n'
                 ')\n'
                 "print(f'height 0: {frontier.count():3d} (trailhead, position) pairs')\n"
                 '\n'
                 'for height in range(1, 10):\n'
                 '    nxt = grid.filter(F.col("h") == height).select(\n'
                 '        F.col("r").alias("nr"), F.col("c").alias("nc")\n'
                 '    )\n'
                 '    frontier = (\n'
                 '        frontier.crossJoin(steps)\n'
                 '        .join(\n'
                 '            nxt,\n'
                 '            (F.col("nr") == F.col("r") + F.col("dr"))\n'
                 '            & (F.col("nc") == F.col("c") + F.col("dc")),\n'
                 '        )\n'
                 '        .select("sr", "sc", F.col("nr").alias("r"), F.col("nc").alias("c"))\n'
                 '        .distinct()\n'
                 '    )\n'
                 "    print(f'height {height}: {frontier.count():3d} pairs')\n"
                 '\n'
                 '# The surviving frontier IS the answer relation: one row per\n'
                 '# (trailhead, reachable summit).\n'
                 'frontier.groupBy("sr", "sc").count().withColumnRenamed(\n'
                 '    "count", "score"\n'
                 ').orderBy("sr", "sc").show()\n'
                 'grid.unpersist()',
 'explore_md': '### Nine joins, counted\n'
               '\n'
               'The cell below runs the same loop as `part1` but prints the frontier size after '
               'every height. Watch it widen as the trails fan out and then narrow as dead ends '
               'fail to join. The last table is each trailhead and its score — read it against '
               'the 5, 6, 5, 3, 1, 3, 5, 3, 5 in the puzzle.',
 'lesson': 'Spark — nine iterative joins up the height gradient',
 'notes': '- **`try_cast`, not `cast`.** Spark 4 runs ANSI mode by default, where casting `"."` '
          "or `split`'s trailing `\"\"` to `int` **raises** instead of returning null. "
          '`try_cast` nulls them so the `isNotNull` filter can drop them. This is the single '
          'most likely thing to break if you rewrite `cells()`.\n'
          '- Those non-digit cells are removed from the relation entirely, which is exactly '
          'right: the smaller published examples use `.` as impassable terrain, and a cell that '
          'does not exist can never satisfy a join condition.\n'
          '- The `.distinct()` belongs **inside** the loop, once per height. Move it to the end '
          'and you get a path count, not a score — a different number, and a different puzzle.\n'
          '- `grid` is `cache()`d because the loop filters it ten times. Without it Spark '
          're-splits and re-explodes the source string on every iteration.\n'
          '- Nine chained joins build a deep lineage, and each `.distinct()` is a shuffle. On a '
          'real grid this is where you would consider checkpointing to cut the plan.\n'
          '- Assumes single-digit heights 0–9 and strictly `+1` steps in the four cardinal '
          'directions. The step table is data, not code — adding diagonals means adding two '
          'rows to `STEPS`, nothing else.\n'
          '- The final `count()` is the answer because a trailhead contributes one row per '
          'distinct summit. There is no separate summation step to get wrong.',
 'summary': 'A topographic map: one digit per cell, height 0 (lowest) through 9 (highest).\n'
            '\n'
            'A **hiking trail** starts at a 0, ends at a 9, moves only up/down/left/right — no '
            'diagonals — and gains exactly **one** height at every step. A **trailhead** is any '
            'height-0 cell, and its **score** is the number of distinct 9s reachable from it by '
            'some trail. Reaching the same 9 by several routes still scores 1.\n'
            '\n'
            '- **Part 1** — sum the scores of every trailhead on the map.',
 'title': 'Hoof It'}
